version: '3.8'
services:
  anetta:
    image: javierantich/anetta-arm64:latest
    container_name: anetta
    environment:
      - ALLOWED_HOSTS=127.0.0.1
    command: python /anetta/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
    
      - ./anetta_config.yml:/anetta/anetta_config.yml
      - ./anetta_requests.csv:/anetta/anetta_requests.csv
      - ./llm_requests.csv:/anetta/llm_requests.csv
      - ./inventory.yml:/anetta/inventory.yml
      - ./inventory_sdl.yml:/anetta/inventory_sdl.yml
      - ./gcp_service_account_credentials.json:/anetta/gcp_service_account_credentials.json
    ports:
      - "8000:8000"
      


  