version: '3.8'
services:
  anetta:
    image: javierantich/anetta-arm64:latest
    container_name: anetta
    environment:
      #if you are planning to run Anetta in a server, add in ALLOWED_HOSTS the IP address Anetta will be reachable in that server
      - ALLOWED_HOSTS=127.0.0.1,localhost
      #if you need Anetta to use a proxy server to reach Internet fill and uncomment the parameters below
      #- HTTP_PROXY=http://your.proxy.server:port
      #- HTTPS_PROXY=https://your.proxy.server:port
      #- NO_PROXY=localhost,127.0.0.1  
    command: python /anetta/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
    
      - ./anetta_config.yml:/anetta/anetta_config.yml
      - ./anetta_requests.csv:/anetta/anetta_requests.csv
      - ./llm_requests.csv:/anetta/llm_requests.csv
      - ./inventory.yml:/anetta/inventory.yml
      - ./inventory_sdl.yml:/anetta/inventory_sdl.yml
      - ./gcp_service_account_credentials.json:/anetta/gcp_service_account_credentials.json
    ports:
      - "8000:8000"
      


  